language: node_js
node_js:
    - "node"
script: node_modules/karma/bin/karma start my.conf.js --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - wget http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/46.0.1/linux-x86_64/en-US/firefox-46.0.1.tar.bz2
    - tar xvjf firefox-46.0.1.tar.bz2
    - sudo ln -s /usr/local/firefox/firefox /usr/bin/firefox
    - npm install
    - node server.js &
